### ISSUE TITLE
Trouble with install_tensorflow(version = "somekindofversion")

### ISSUE THREAD

**Issue by gergiu** [rstudio/tensorflow-blog#8]
Hi, I'm having trouble in installing a good version of tensorflow on my laptop. 
First I installed a basic version of it (just using install_tensorflow()) but when I want to confirm that the installation succeeded: 

_> library(tensorflow)
> sess = tf$Session()
2018-08-28 12:06:53.362284: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> hello <- tf$constant('Hello, TensorFlow!')
> sess$run(hello)
b'Hello, TensorFlow!'_

So I ry removing myconda environment and then re-installing with:

_library(reticulate)
conda_remove("r-tensorflow")
install.packages("tensorflow")
library(tensorflow)

install_tensorflow(version = "somekindofversion")_

but I get this error: Error: Error 2 occurred installing packages into conda environment r-tensorflow 

This is the entire script:

install_tensorflow(version = "https://github.com/fo40225/tensorflow-windows-wheel/blob/master/1.4.0/py36/CPU/avx2/tensorflow-1.4.0-cp36-cp36m-win_amd64.whl")
Creating r-tensorflow conda environment for TensorFlow installation...
Solving environment: ...working... done

## Package Plan ##

  environment location: G:\G_PROGRAMMI\Anaconda3\envs\r-tensorflow

  added / updated specs: 
    - python=3.6

The following NEW packages will be INSTALLED:

    certifi:        2018.8.24-py36_1  
    pip:            10.0.1-py36_0     
    python:         3.6.6-hea74fb7_0  
    setuptools:     40.2.0-py36_0     
    vc:             14.1-h0510ff6_3   
    vs2015_runtime: 15.5.2-3          
    wheel:          0.31.1-py36_0     
    wincertstore:   0.2-py36h7fe50ca_0

Preparing transaction: ...working... done
Verifying transaction: ...working... 
SafetyError: The package for setuptools located at G:\G_PROGRAMMI\Anaconda3\pkgs\setuptools-40.2.0-py36_0
appears to be corrupted. The path 'Scripts/easy_install.exe'
has a sha256 mismatch.
  reported sha256: 993203a406e04936a07829b1f482fd27d739b640482e213f4c49ea1ee78a5fcf
  actual sha256: 0cc372d47e0e71c25012697ae0a2feca19cfa46caccb872a555c3669e79f701b

SafetyError: The package for wheel located at G:\G_PROGRAMMI\Anaconda3\pkgs\wheel-0.31.1-py36_0
appears to be corrupted. The path 'Scripts/wheel.exe'
has a sha256 mismatch.
  reported sha256: 993203a406e04936a07829b1f482fd27d739b640482e213f4c49ea1ee78a5fcf
  actual sha256: 2a882e6c7ea316634261d68f7ccb7aadc34fe864b4b834611c9a4cd26efc9d35

done
Executing transaction: ...working... done
#
# To activate this environment, use:
# > activate r-tensorflow
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#

Determining latest installable release of TensorFlow...done
Installing TensorFlow...
Collecting tensorflow==1.4.0 from https://github.com/fo40225/tensorflow-windows-wheel/blob/master/1.4.0/py36/CPU/avx2/tensorflow-1.4.0-cp36-cp36m-win_amd64.whl
  Downloading https://github.com/fo40225/tensorflow-windows-wheel/blob/master/1.4.0/py36/CPU/avx2/tensorflow-1.4.0-cp36-cp36m-win_amd64.whl
Exception:
Traceback (most recent call last):
  File "G:\G_PROGRAMMI\Anaconda3\envs\r-tensorflow\lib\site-packages\pip\_internal\basecommand.py", line 228, in main
    status = self.run(options, args)
  File "G:\G_PROGRAMMI\Anaconda3\envs\r-tensorflow\lib\site-packages\pip\_internal\commands\install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "G:\G_PROGRAMMI\Anaconda3\envs\r-tensorflow\lib\site-packages\pip\_internal\resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "G:\G_PROGRAMMI\Anaconda3\envs\r-tensorflow\lib\site-packages\pip\_internal\resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "G:\G_PROGRAMMI\Anaconda3\envs\r-tensorflow\lib\site-packages\pip\_internal\resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "G:\G_PROGRAMMI\Anaconda3\envs\r-tensorflow\lib\site-packages\pip\_internal\operations\prepare.py", line 310, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "G:\G_PROGRAMMI\Anaconda3\envs\r-tensorflow\lib\site-packages\pip\_internal\download.py", line 837, in unpack_url
    progress_bar=progress_bar
  File "G:\G_PROGRAMMI\Anaconda3\envs\r-tensorflow\lib\site-packages\pip\_internal\download.py", line 678, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "G:\G_PROGRAMMI\Anaconda3\envs\r-tensorflow\lib\site-packages\pip\_internal\utils\misc.py", line 575, in unpack_file
    flatten=not filename.endswith('.whl')
  File "G:\G_PROGRAMMI\Anaconda3\envs\r-tensorflow\lib\site-packages\pip\_internal\utils\misc.py", line 460, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "G:\G_PROGRAMMI\Anaconda3\envs\r-tensorflow\lib\zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "G:\G_PROGRAMMI\Anaconda3\envs\r-tensorflow\lib\zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
 **Error: Error 2 occurred installing packages into conda environment r-tensorflow** 

The version I tried to install is takek from "https://github.com/fo40225/tensorflow-windows-wheel/blob/master/1.4.0/py36/CPU/avx2/tensorflow-1.4.0-cp36-cp36m-win_amd64.whl"

Any help would be greatly appreciated, thanks!

**Comment by skeydan** [comment]
Hi,

please try the very first method again.
This

```
\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
```

is not an error; - it means that the compiled binary is not optimized for your environment, but this will probably happen in every case where you don't compile tensorflow from source.
It will work just fine all the same :-)

**Comment by gergiu** [comment]
Thank you, 

so I just ignore it :-)
